{{- range .Values.sealedSecrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  encryptedData:
    {{- range $key, $val := .encryptedData }}
    {{ $key }}: {{ $val }}
    {{- end }}
  template:
    metadata:
      name: {{ .name }}
      namespace: {{ $.Release.Namespace }}
      {{- with .templateLabels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .templateAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    type: {{ .type | default "Opaque" }}
{{- end }}
