{
 "title": "Cluster Logs",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Tenant", "query": "loki" },
   {
    "name": "namespace",
    "query": {}
   },
   {
    "name": "pod",
    "query": {}
   },
   {
    "name": "level",
    "label": "Level",
    "query": "critical,error,warn,info,debug,trace,unknown"
   },
   { "name": "search_filter", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({job=~\".+\", namespace=~\"$namespace\", level=~\"$level\", level!=\"\"} [$__auto]))",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({job=~\".+\", namespace=~\"$namespace\", level=~\"error|critical\"} [$__auto]))",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "Top Logging Pods",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum by (pod) (count_over_time({job=~\".+\", namespace=~\"$namespace\", pod!=\"\"} [$__range])))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Top Logging Pods",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (pod) (count_over_time({job=~\".+\", namespace=~\"$namespace\", pod!=\"\"} [$__range])))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{job=~\".+\", namespace=~\"$namespace\", pod=~\"$pod\", level=~\"$level\"} | json $search_filter"
    }
   ]
  }
 ]
}