{{- if .Values.cloudflare.tunnel_token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tunnel-token
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  token: {{ .Values.cloudflare.tunnel_token | quote }}
{{- end }}
